### ISSUE TITLE
Memory leak when no tags are detected

### ISSUE THREAD

**Issue by prclibo** [alddiaz/MATLAB_AprilTag3#2]
Hi, Thanks for this handy code. I am pretty confused on why Corke's toolbox is missing these files.

https://github.com/alddiaz/MATLAB_AprilTag3/blob/8b49fb8e8e5149bd8cc8d1bd0a654b5661dfff69/Machine%20Vision%20Toolbox%20for%20MATLAB/vision/mex/apriltags.c#L63

I found the above line results a memory leak, as `out` has not been allocated yet. Probably should remove?

**Comment by alddiaz** [comment]
Hi! Your're welcome, I'm glad that you find my code instrumental :D
I've just made some tests and I think the array should be indeed destroyed since it is given a memory space on creation

https://github.com/alddiaz/MATLAB_AprilTag3/blob/8b49fb8e8e5149bd8cc8d1bd0a654b5661dfff69/Machine%20Vision%20Toolbox%20for%20MATLAB/vision/mex/apriltags.c#L39

Otherwise, you can just wipe out L63 on your code if it is giving you much problem, this shouldn't affect the performance at all.

Please, let me know if you got to solve the problem.

Regards,

Aldo

**Comment by prclibo** [comment]
@alddiaz Thanks for the reply. `mxArray *out; ` does not allocate memory. It is just a pointer variable which will be release automatically when the function returns.

Memory allocation happens at
https://github.com/alddiaz/MATLAB_AprilTag3/blob/8b49fb8e8e5149bd8cc8d1bd0a654b5661dfff69/Machine%20Vision%20Toolbox%20for%20MATLAB/vision/mex/apriltags.c#L71

The `mxDestroyArray` is before this allocation.

**Comment by alddiaz** [comment]
Oh your're :100: right! I have just updated the code. Thanks for pointing to the bug :+1: !
Let me know if you fixed the memory leakage problem and also in case you find more glitches.
